### PR TITLE
hotfix: fixed some import errors and an improper type in MoveByCVY

### PR DESCRIPTION
**Pull request by mjspeck**
The `daide_seas` attribute should be a container of location objects, not strings.

### CODE REVIEW

**Review by byung-o — APPROVED** [review]
lgtm

**Comment by aphedges** [comment]
In addition, if I'm not mistaken, this will allow coasts to be added. This means that the grammar cannot parse some DAIDE strings created from this object.

**Comment by mjspeck** [comment]
Yeah, that's fair. I'll keep this out of the main branch and do a workaround in our code.

> I'm very concerned about this. It breaks backwards compatibility very close to the deadline, and it doesn't align with the grammar. In addition, you approved my change to make the behavior this way.
> 
> At the very least, can you please add automatic conversion of string arguments like I did elsewhere?

**Comment by aphedges** [comment]
Thank you very much!

**Pull request closed without merging**
