### PR TITLE
Fix/#81 sorted powers

### PR DESCRIPTION
**Pull request by mjspeck**
Any class that has a `self.powers` attribute now has that attribute sorted in ascending alphabetical order.

Closes: #81

### CODE REVIEW

**Comment by bpshaver** [comment]
@mjspeck From the tests that are failing I would guess that we simply need to sort the powers in the existing test cases?

**Comment by bpshaver** [comment]
LGTM

**Review by bpshaver — APPROVED** [review]
LGTM

**Comment by aphedges** [comment]
What is the status of this PR? I personally would find this change useful.

**Comment by bpshaver** [comment]
> What is the status of this PR? I personally would find this change useful.

I think we just haven't gotten around to merging it, maybe? I'll go ahead and so now.

**Comment by aphedges** [comment]
Thank you very much!

**Pull request merged**
